### ISSUE TITLE
get the context.connectionid

### ISSUE THREAD

**Issue by BlueDragon709** [NightAngell/SignalR_UnitTestingSupport#15]
What do you want to know?
Hello i am writing tests using this library.

I would like to know which connection id the library generates.
or How do i get the connectionId while testing?

**Comment by NightAngell** [comment]
> ### **Which connection id the library generates?**

I`m not sure if I understood this question, but I try answer to it. This is entire code responsible for setup ConnectionId before each test ([source on github](https://github.com/NightAngell/SignalR_UnitTestingSupport/blob/master/SignalR_UnitTestingSupportCommon/Hubs/Internal/HubUnitTestsBaseCommon.cs)):
```csharp
string connId = System.Guid.NewGuid().ToString();

//Setup ConnectionId for Microsoft.AspNetCore.SignalR.Hub Context property.
ContextMock.Setup(x => x.ConnectionId).Returns(connId);
```
In short: ConnectionId is GUID and is unique per test. 
>###  **How do i get the connectionId while testing?**
For example:
```csharp
public void ConnectionIdAlwaysSameInScopeOfTest()
{
    var hub = new V101FeaturesHub();
    AssignToHubRequiredProperties(hub);
    string connId1 = ContextMock.Object.ConnectionId;
    string connId2 = ContextMock.Object.ConnectionId;

    Assert.AreEqual(connId1, connId2);
}
```
More examples here:
- [For NUnit](https://github.com/NightAngell/SignalR_UnitTestingSupport/blob/master/TestsWithUnitTestingSupport/Hubs/V1.0.1FeaturesTests.cs)
- [For xUnit](https://github.com/NightAngell/SignalR_UnitTestingSupport/blob/master/TestsWithUnitTestingSupportXUnit/Hubs/V1.0.1FeaturesTests.cs)
- [For MSTest](https://github.com/NightAngell/SignalR_UnitTestingSupport/blob/master/TestsWithUnitTestingSupportMSTest/Hubs/V1.0.1FeaturesTests.cs)


> And remember, you cannot get ConnectionId when you use Hub through IHubContext (simply because you are not connected to the hub therefore there is no Context). For more details read [this](https://docs.microsoft.com/pl-pl/aspnet/core/signalr/hubcontext?view=aspnetcore-2.2).

**Comment by BlueDragon709** [comment]
My hub has a couple of static dictionaries.
One of my functions returns a list of users.
When i do my tests 1 by 1 the pass.
But when i run them all that one function gets the users from the other tests back.

hub.Dispose() doesn't work.

How do I clear the memory of the hub when a test finishes?

**Comment by NightAngell** [comment]
You mean clear that static dictionaries?
I see two possibilities. 

> ### **First (Recommended):**

After each test clear static collection, for example:
```csharp

public class MyTests 
{
    //[TearDown] //For NUnit
    //[TestCleanup] //For MSTest
    public void ClearAfterEachTest()
    {
        ourHub.ourDictionary.Clear();
    }
}

//For xUnit
public class MyTests : IDisposable
{
    public void Dispose()
    {
        ourHub.ourDictionary.Clear();
    }
}
```

> ### **Second (If you need clear that memory just for tests, strongly not recommended):** 

Override Dispose(bool disposing) method in your hub and define it (because default dispose implementation can`t even know about collections defined in inheriting class, but it is probably not what you want. (curiosity: [default implementation](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/server/Core/src/Hub.cs) of that method do nothing)).
